name: CI

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
          extraPullNames: nixpkgs-terraform
      - run: nix profile install --accept-flake-config nixpkgs#devenv
      - run: devenv test
