name: CI

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - run: nix-env -iA devenv -f https://github.com/NixOS/nixpkgs/tarball/2b8521c464b0f0c587839545b9d70b2d0b7574d0
      - run: devenv test
        env:
          NIXPKGS_ALLOW_UNFREE: 1
